### ISSUE TITLE
image metric is not correctly registered for deserialization from DatasetProfileView

### ISSUE THREAD

**Issue by jamie256** [whylabs/whylogs#1009]
## Description

You can repro the issue reported by adding this at the end of the Image_Logging notebook (or replace the WhylabsWriter part):
https://colab.research.google.com/github/whylabs/whylogs/blob/mainline/python/examples/advanced/Image_Logging.ipynb
```
from whylogs.core import DatasetProfileView
view.write(path="test.bin")
deserialized_view = DatasetProfileView.read("test.bin")
```

Which results in an error:

```
column_profile_view.py:129, in ColumnProfileView.from_protobuf(cls, msg)
    127         metric_class = _METRIC_DESERIALIZER_REGISTRY[m_name]
    128     else:
--> 129         raise UnsupportedError(f"Unsupported metric: {m_name}")
    130 else:
    131     metric_class = m_enum.value


UnsupportedError: Unsupported metric: image
```

## Suggestions

Modify ImageMetric to correctly register an entry in _METRIC_DESERIALIZER_REGISTRY and allow MultiMetric support for deserialization from ColumnProfileView

- [x] I have reviewed the [Guidelines for Contributing](https://github.com/whylabs/whylogs/blob/mainline/.github/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/whylabs/whylogs/blob/mainline/.github/CODE_OF_CONDUCT.md).

**Comment by richard-rogers** [comment]
`MultiMetric`is not a dataclass, so it isn't calling the `Metric::__post_init__()`. Also, since the registration only happens in the metric constructors, the non-standard metrics aren't registered until at least one gets instantiated. 

I'll add code that registers them on `import`.
