### ISSUE TITLE
Unable to import whylogs

### ISSUE THREAD

**Issue by mayankjobanputra** [whylabs/whylogs#1041]
## Description

Unable to import whylogs 

`>>> import whylogs as why`
gives `AttributeError: module 'site' has no attribute 'getsitepackages'`

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/monk/why/lib/python3.7/site-packages/whylogs/__init__.py", line 29, in <module>
    from .api.usage_stats import emit_usage as __emit_usage_stats
  File "/home/monk/why/lib/python3.7/site-packages/whylogs/api/usage_stats/__init__.py", line 30, in <module>
    _SITE_PACKAGES = site.getsitepackages()
AttributeError: module 'site' has no attribute 'getsitepackages'
`

- System info
  - Operating system and version: Ubuntu 18.04
  - Tried on Python3.7, Python3.8, Python3.9
  - virtualenv
 
- Steps to reproduce:
  - Create a virtualenv -- `virtualenv why --python=python3.7`
  - activate the virtualenv -- `source why/bin/activate`
  - `pip install whylogs`
  - `python`
  - `import whylogs`

Although I was able to install this on colab. I don't know why it's not working on my local machine.

- [x] I have reviewed the [Guidelines for Contributing](https://github.com/whylabs/whylogs/blob/mainline/.github/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/whylabs/whylogs/blob/mainline/.github/CODE_OF_CONDUCT.md).

**Comment by jamie256** [comment]
Its a virtualenv issue, I was able to repro on docker image using ubuntu 18.04, thanks for the details, fix pending.

**Comment by mayankjobanputra** [comment]
Somehow it works out of the box on Colab. I will keep looking for a solution/workaround for this also. :)

**Comment by mayankjobanputra** [comment]
Thanks a lot @jamie256 :)

**Comment by jamie256** [comment]
I published a dev release off mainline after this was merged if you want to test this out:
`pip install whylogs==1.1.21.dev0`

**Comment by mayankjobanputra** [comment]
It's working :1st_place_medal:
