### ISSUE TITLE
Support human-readable datetime for output paths

### ISSUE THREAD

**Issue by andyndang** [whylabs/whylogs#108]
From the community slack:

> and a followup question is in the yaml file when i am calling the $dataset_timestamp variable, it outputs a unix timestamp. Is there any way i can use this variable and still get a normal date like ‘2020-12-18’. Actually i am using this variable to name the subfolders and i want them to be dated normally, not in a unix timestamp

This is currently not supported by whylogs. Simply because we couldn’t decide what granularity to support (if you go down to seconds you have : and it makes linux path very unhappy).

We can probably have some precanned template value such as `dataset_timestamp_iso8061_date` (you'll get `YYYY-MM-DD`), `dataset_timestamp_iso8061_hour` and get `YYYY-MM-DD"T"HH` (like 2020-12-18T09)

Further granularity probably should be thought through since `ISO 8061` involves `:` characters, which Unix file system path will scream at you

**Comment by lalmei** [comment]
This is partially supported with log rotation with time since those force a suffix for in readable format, however it is currently only in UTC.

**Comment by jamie256** [comment]
Closing: already use datetime template for log rotation, and can update this behavior in v1.
