### ISSUE TITLE
Rolling logger doesn't appear to wipe internal state after writing

### ISSUE THREAD

**Issue by naddeoa** [whylabs/whylogs#1083]
## Description

I expect the rolling logger to get rid of all of its stored profile state after it writes, or else it would end up writing subsequent profiles that include that same data. Through testing, there are two things that lead me to believe that isn't the case:

- After a write, the rolling logger still has access to the same profile, apparently stored as `self._current_profile`.
- You can write multiple times in a row without logging and each one will claim to write something, even though no new data has been written.

I can confirm that there are multiple profiles being uploaded in our platform as well, it isn't just a messaging issue.

- System info
  - Operating system and version: Ubuntu 22.04
  - Browser and version: n/a
- Steps to reproduce:

```
git clone git@github.com:naddeoa/whylogs-writer-bug-repro.git writer-bug
cd writer-bug
make
```

![image](https://user-images.githubusercontent.com/1233709/217654509-ed87fa0c-442d-4bb6-bd82-bfe5ba1f2d51.png)

## Related

Relates to organization/repo#number 

- [ ] I have reviewed the [Guidelines for Contributing](https://github.com/whylabs/whylogs/blob/mainline/.github/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/whylabs/whylogs/blob/mainline/.github/CODE_OF_CONDUCT.md).

**Comment by naddeoa** [comment]
It also looks like I'm getting warning message about my dataset timestamps being slightly in the future but I haven't done anything to configure that at all, I'm just using the default internal logic.

**Comment by andyndang** [comment]
That's really strange. Am I hallucinating that these two lines don't do what I expect them to do: https://github.com/whylabs/whylogs/blob/mainline/python/whylogs/api/logger/rolling.py#L168

```
        old_profile = self._current_profile

        self._current_profile = DatasetProfile(
            schema=self._schema,
            dataset_timestamp=dataset_timestamp,
        )
```

**Comment by andyndang** [comment]
Oh by default we don't skip empty profiles so we will always publish them.

See: https://whylogs.readthedocs.io/en/latest/api/whylogs/api/logger/rolling/index.html?highlight=skip_empty#attributes

I don't think this is a bug :). We want the logger to "ping" our endpoint even if there's no data

**Comment by jamie256** [comment]
I am debugging this, it does not repro, the claims in the bug are false as its not the same profile. We upload empty profiles subsequently after wiping the state.

**Comment by jamie256** [comment]
If you modify your repro script you can see the id changes, also the counts are all zero in the profile's metrics after rollover:
e.g. debug through it with a watch expression:
`rolling_logger._current_profile._columns['col1']._metrics['counts'].n.value`

```python
    df = pd.DataFrame(data={"col1": [1, 2], "col2": [3.0, 4.0], "col3": ["a", "b"]})
    rolling_logger = y.logger(mode="rolling", interval=5, when="M", base_name="profile_")
    rolling_logger.append_writer('local')

    rolling_logger.log(df)
    initial_profile_id = id(rolling_logger._current_profile)
    rolling_logger._do_rollover()
    post_rollover_profile_id = id(rolling_logger._current_profile)
    print(f"initially id(rolling_logger._current_profile) {initial_profile_id} after rollover it is {post_rollover_profile_id}")
 ```
 
 This outputs:
 initially id(rolling_logger._current_profile) 140226791204896 after rollover it is 140226791204800

**Comment by andyndang** [comment]
@jamie256 I think we have an issue around timestamp I suspect. New profiles are timed with `time.time()` and I'm not sure how that's different from utc timestamp.

Also, we should log a debug statement that we detect an empty profile and we are sending it ot WhyLabs
