### ISSUE TITLE
Issues with Embeddings Distance and NotebookProfileVisualizer

### ISSUE THREAD

**Issue by FelipeAdachi** [whylabs/whylogs#1148]
## Description

Trying to visualize two profiles with `EmbeddingMetric` leads to an error in `summary_drift_report`:

`AttributeError: 'NoneType' object has no attribute 'hll'`

Also, the calculated column `.closest` fails to be displayed in both `profile_summary()` and `distribution_chart`

**Comment by datatalking** [comment]
@FelipeAdachi 

It actually is processing non-type correctly because non-type doesn't have that attribute.

If you can provide a sample data set that reproduces this, I can take a look at it this issue next week for you.

**Comment by FelipeAdachi** [comment]
@datatalking hi, Andrew!
thank you for your interest and offer!

The following code should reproduce this error:

```python
import numpy as np

import whylogs as why
from whylogs.core.resolvers import MetricSpec, ResolverSpec
from whylogs.core.schema import DeclarativeSchema
from whylogs.experimental.extras.embedding_metric import (
    DistanceFunction,
    EmbeddingConfig,
    EmbeddingMetric,
)
from whylogs.viz import NotebookProfileVisualizer


config = EmbeddingConfig(
    references=np.array([[0.01, 0.01, 0.01], [1, 1, 1]]),
    labels=["B", "A"],
    distance_fn=DistanceFunction.euclidean,
)
schema = DeclarativeSchema([ResolverSpec(column_name="col1", metrics=[MetricSpec(EmbeddingMetric, config)])])
sample_data = np.array([[0.1, 0.1, 0.1], [0.6, 0.6, 0.6], [2, 2, 2]])
profile = why.log(row={"col1": sample_data}, schema=schema)
view = profile.view()

visualization = NotebookProfileVisualizer()
visualization.set_profiles(target_profile_view=view, reference_profile_view=view)

visualization.summary_drift_report()
```

If you replace the last line to `visualization.profile_summary()`  the visualization is rendered, but the `col1.closest` is not displayed. Although this is probably a separate issue.

Let me know if you'll get to work on this, and if I can help you with anything else!
