### ISSUE TITLE
Use pydantic to parse whylogs config

### ISSUE THREAD

**Issue by andyndang** [whylabs/whylogs#119]
We're using marshmallow to parse whylogs config from YAML

However, Pydantic is much more powerful as it allows users to set config via various mechanims, from YAML, JSON to Environment settings.

We should consider moving to pydantic

**Comment by lalmei** [comment]
Since protobuf now supports python 3.9, nothing is blocking this issue.

**Comment by jamie256** [comment]
whylogs v1 doesn't have yaml config files.
