### ISSUE TITLE
Pypi metadata are missing/incorrect

### ISSUE THREAD

**Issue by andyndang** [whylabs/whylogs#120]
* Missing short description:
![image](https://user-images.githubusercontent.com/26821974/104046994-c4489480-5195-11eb-89e6-5a20f7364543.png)
* Incorrect License (should be Apache v2)
![Screen Shot 2021-01-08 at 9 42 52 AM](https://user-images.githubusercontent.com/26821974/104047061-e215f980-5195-11eb-8278-26f88bd236c9.png)
* The project links/documentations/stars/forks etc are linked to pyscaffold rather than whylogs (we used pyscaffold to set up the package structure)

**Comment by lalmei** [comment]
Fixed with uploading the lastest released v0.1.13
