### ISSUE TITLE
Make any ResultSet writable to WhyLabs

### ISSUE THREAD

**Issue by FelipeAdachi** [whylabs/whylogs#1250]
## Description

With https://github.com/whylabs/whylogs/pull/1248, Segmented, Reference, ResultSets can be written to WhyLabs. However, other ResultSets are not directly writable. We should make all types of ResultSets writable to WhyLabs.

## Related

Relates to organization/repo#number 

- [x] I have reviewed the [Guidelines for Contributing](https://github.com/whylabs/whylogs/blob/mainline/.github/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/whylabs/whylogs/blob/mainline/.github/CODE_OF_CONDUCT.md).

**Comment by jamie256** [comment]
Richard has changes that support writing results sets pending, so assigning to him.
