### ISSUE TITLE
Exception with profiling pandas datetime64[ns] columns

### ISSUE THREAD

**Issue by tdoehmen** [whylabs/whylogs#1262]
## Description

I'm encoutering an issue with pandas columns of type `datetime64[ns]`, containing `pd.Timestamp` values:

`TypeError: Converting from datetime64[ns] to int32 is not supported. Do obj.astype('int64').astype(dtype) instead`

Code to reproduce:

```
import pandas as pd
import whylogs as why

df_test = pd.DataFrame({"dt": pd.date_range(start='2022-01-01', periods=10, freq='H', tz=None)})

why.log(df_test)
```

- System info
  - Operating system and version: Windows 11
  - Browser and version: -
  - Pandas Version: tested on 1.5.3 and 2.0.2
  - Whylogs version: 1.1.43
- Steps to reproduce:
  - See code above
  - Next step

## Related

Relates to organization/repo#number 

- [ ] I have reviewed the [Guidelines for Contributing](https://github.com/whylabs/whylogs/blob/mainline/.github/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/whylabs/whylogs/blob/mainline/.github/CODE_OF_CONDUCT.md).

**Comment by jamie256** [comment]
Thanks for filing the issue and the concise repro @tdoehmen, we'll get this fixed!

I can reproduce this error on a Windows setup, but not Ubuntu.

Note: whylogs doesn't extract statistics on datetime/timestamp columns yet, but we certainly should not raise an error!

**Comment by tdoehmen** [comment]
Thanks, that makes sense. I wasn't aware that Date types are not supported yet. 

I guess I could get around it with a [custom resolver](https://nbviewer.org/github/whylabs/whylogs/blob/mainline/python/examples/basic/Schema_Configuration.ipynb) that excludes those columns or adds a custom metric for timestamps.
