### ISSUE TITLE
Custom Metrics on Spark

### ISSUE THREAD

**Issue by tdoehmen** [whylabs/whylogs#1264]
## Description

#1262 lead me to a potential issue related to spark: 

I noticed that when I follow the [custom metric](https://whylogs.readthedocs.io/en/latest/examples/advanced/Custom_Metrics.html?highlight=custom%20metrics) tutorial and use the custom schema on Spark (`collect_dataset_profile_view(input_df=df,schema=schema)`), I get the following error:

`whylogs.core.errors.UnsupportedError: Unsupported metric: histogram`. 

Are custom metrics supported at all in spark, if not is support planned?

A couple of question around that (apologies if they are a bit out of context):
1) The whylogs/java [readme](https://github.com/whylabs/whylogs/blob/mainline/java/README.md) sais that v.1.0.0 support is coming soon, but from the spark docs [here](https://docs.whylabs.ai/docs/spark-integration) it seems that v.1.0.0 is already supported. Which one is true?
2) There are some incompatabilities between Spark <=3.1 and Pandas 2.0. Among others, df.append and df.iteritems were removed which pyspark internally uses. Are there any plans to move whylogs to a newer Spark version?
3) Is it even recommended to use this spark integration or would you recommend going via [Fugue](https://whylogs.readthedocs.io/en/latest/examples/integrations/Fugue_Profiling.html?highlight=spark)?

- System info
  - Operating system and version: Ubuntu 18.04
  - Browser and version: -
  - Spark: 3.1.1
  - Python: 3.10
  - Whylogs: latest whylogs["spark"] from pypi, .jar built from whylogs/java master
- Steps to reproduce:
  - [whylogs_spark.zip](https://github.com/whylabs/whylogs/files/11623150/whylogs_spark.zip)

## Related

Relates to organization/repo#number 

- [ ] I have reviewed the [Guidelines for Contributing](https://github.com/whylabs/whylogs/blob/mainline/.github/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/whylabs/whylogs/blob/mainline/.github/CODE_OF_CONDUCT.md).

**Comment by richard-rogers** [comment]
The custom metrics need to be registered. I should update the notebook to reflect that. It might also be nice to have a class decorator for it.

**Comment by richard-rogers** [comment]
Looks like there's already a `@custom_metric` decorator.

**Comment by tdoehmen** [comment]
Perfect, thanks, that did that trick :) Mind shedding some light on the whylogs-java vs fugue[spark] question? They both seem to work for my purpose, but I wonder if there are any individual drawback/benefits for either of them.
