### ISSUE TITLE
metric udfs should support a list of columns

### ISSUE THREAD

**Issue by andrewelizondo** [whylabs/whylogs#1269]
## Description
Currently dataset udfs allow for specifying a list of input columns, while metric udfs produce a different kind of output it would be great to be able to specify a specific list of columns to apply them to instead of just a single column or a type.

## Suggestions
change the col_name variable to accept a list and iterate over it vs a string

- [x] I have reviewed the [Guidelines for Contributing](https://github.com/whylabs/whylogs/blob/mainline/.github/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/whylabs/whylogs/blob/mainline/.github/CODE_OF_CONDUCT.md).

**Comment by tdoehmen** [comment]
+1

**Comment by FelipeAdachi** [comment]
reopening as this is still relevant
