### ISSUE TITLE
UDFs should have unique identifiers

### ISSUE THREAD

**Issue by andrewelizondo** [whylabs/whylogs#1299]
## Description

Currently you can only apply a single udf to a method and can only apply a single named udf to a column. This seems like it will present scaling issues in the future.
As a user I'd like to apply multiple udfs to the same method to apply to different columns without needing to replicate the method over and creating code bloat.

- [x] I have reviewed the [Guidelines for Contributing](https://github.com/whylabs/whylogs/blob/mainline/.github/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/whylabs/whylogs/blob/mainline/.github/CODE_OF_CONDUCT.md).

**Comment by FelipeAdachi** [comment]
reopening as this is still relevant
