### ISSUE TITLE
Support configurable top-k values

### ISSUE THREAD

**Issue by andyndang** [whylabs/whylogs#137]
Currently whylogs collects a fixed number of top-k values (128 entries).

Users should be able to:
* Disable top-k value collection (privacy concerns)
* Enable for a number of features (whitelisting)
* Or enable all, but disable on a number of features (blacklisting)
* Customize k values
*

**Comment by lalmei** [comment]
+1

**Comment by lalmei** [comment]
The other option is hash those keys, and top values with a gpg key, but this is faster

**Comment by jamie256** [comment]
1.0.0 has MetricConfig which allows specifying if a user wants frequent items tracking on, and how many to track:
https://github.com/whylabs/whylogs/blob/mainline/python/whylogs/core/metrics/metrics.py#L41-L42
and custom resolvers: https://github.com/whylabs/whylogs/blob/mainline/python/whylogs/core/resolvers.py#L50
