### ISSUE TITLE
[MAJOR] Using Apache Arrow for managing segment datasets instead of in-memory cache

### ISSUE THREAD

**Issue by andyndang** [whylabs/whylogs#138]
Proposal: using Apache Arrow to manage multiple datasets instead of relying in memory

### Motivation:
* Reduce memory footprint of whylogs when running with multiple segments
* Apache Arrow allows us to use disk to reduce memory access

### Challenges:
* Arrow + Protobuf will require ser/der and that can be challenging. Long term we might consider re implementing protobuf format using Apache Arrow. Or mappping Protobuf schema to Parquet schema
* Arrow only expects write once read many. Also Java API is much more difficult to integrate with (we need feature parity)

**Comment by jamie256** [comment]
consider for 1.1.0 for Arrow support

**Comment by andyndang** [comment]
This is stale since we probably will need to revisit the design
