### ISSUE TITLE
bumpversion job breaking the release CI

### ISSUE THREAD

**Issue by FelipeAdachi** [whylabs/whylogs#1413]
## Description

On the latest release (1.3.11), the release CI hit an error related to bumpversion:
https://github.com/whylabs/whylogs/actions/runs/6632378672/job/18017939443#step:7:65

- [X] I have reviewed the [Guidelines for Contributing](https://github.com/whylabs/whylogs/blob/mainline/.github/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/whylabs/whylogs/blob/mainline/.github/CODE_OF_CONDUCT.md).

**Comment by jamie256** [comment]
I regenerated the token we use for these steps. releases 1.3.12-13 worked without hitting this error, closing.
