### ISSUE TITLE
Calculating drift scores non-interactively broken for images

### ISSUE THREAD

**Issue by djalusic** [whylabs/whylogs#1422]
## Description

When applied to profiles generated for images, `whylogs.viz.drift.column_drift_algorithms.calculate_drift_score` returns only `{'image': None}`, whereas the platform is able to show results of data drift detection as well as the plot generated by `summary_drift_report` method of `NotebookProfileVisualizer`.

Looking at the source code of the `summary_drift_report` I noticed that in one of the steps the function `whylogs.migration.uncompound._uncompound_dataset_profile` was used on the target and reference profiles. Once I applied it to my profiles, `calculate_drift_score` returned expected results for image features.
For tabular data, `calculate_drift_score` works without applying the `_uncompound_dataset_profile` function.

- System info
  - Operating system and version: macOS 13.4.1 -->
- Steps to reproduce:
  - [here](https://colab.research.google.com/drive/1rgRTu0MWHr7sMk5a-5sarDcgkzIXekVz?usp=sharing) you can find a Colab notebook reproducing the issue

![image](https://github.com/whylabs/whylogs/assets/43535016/3479cd84-8f12-4ff4-97e1-4ace42bf5592)
![image](https://github.com/whylabs/whylogs/assets/43535016/d54db2c6-7e8c-4993-8ecc-d8006c79e246)

## Suggestions

- enable calculating data drift and other operations on images as for tabular data, so it is not needed to apply private functions (`_uncompound_dataset_profile`) previously

- [x] I have reviewed the [Guidelines for Contributing](https://github.com/whylabs/whylogs/blob/mainline/.github/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/whylabs/whylogs/blob/mainline/.github/CODE_OF_CONDUCT.md).

**Comment by jamie256** [comment]
Thanks for filing the issue and the details @drajsel!

Assigning to @FelipeAdachi to take a look.

**Comment by FelipeAdachi** [comment]
Thank you for raising this and for the clear explanation @drajsel!

I just pushed a PR to address this: https://github.com/whylabs/whylogs/pull/1424.

It should be included in next week's whylogs release.
