### ISSUE TITLE
Pillow vulnerabilities

### ISSUE THREAD

**Issue by matsair** [whylabs/whylogs#1463]
## Description

There are multiple [osv](https://osv.dev/) vulnerability issues with the Pillow 9.x package dependency. An update to 10.x (https://github.com/whylabs/whylogs/blob/mainline/python/pyproject.toml#L68) is currently not possible.

Some vulnerabilities:
- https://osv.dev/vulnerability/GHSA-3f63-hfp8-52jq
- https://osv.dev/GHSA-56pw-mpj4-fxww
- https://osv.dev/GHSA-8ghj-p4vj-mr35

## Steps to reproduce:
  - `poetry install`
  - `osv-scanner --lockfile poetry.lock` (https://github.com/google/osv-scanner)

![image](https://github.com/whylabs/whylogs/assets/5218859/f9519864-ea7f-4671-82ca-4dfee40af389)

## Suggestions

Could we update Pillow to its latest version?

- [x] I have reviewed the [Guidelines for Contributing](https://github.com/whylabs/whylogs/blob/mainline/.github/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/whylabs/whylogs/blob/mainline/.github/CODE_OF_CONDUCT.md).

**Comment by jamie256** [comment]
changes merged to allow newer versions of PIL and updates lock file. Slated for next whylogs release, 1.4.1

**Comment by jamie256** [comment]
released in version 1.4.1
