### ISSUE TITLE
What are the different metrics mentioned

### ISSUE THREAD

**Issue by pradeepdev-1995** [whylabs/whylogs#1473]
I could see multiple metrics,when i call the code
```
import whylogs as why
from langkit.whylogs.samples import load_chats
chats = load_chats()
results = why.log(chats)
```
![Screenshot from 2024-02-28 18-27-30](https://github.com/whylabs/whylogs/assets/41164884/f6459a2b-0018-4f73-96d9-b586b6723f81)
What does these metircs actually meant? Where can i find the documentation?

**Comment by FelipeAdachi** [comment]
Each row in the picture represents a Langkit metric, whose documentation can be found here:
https://github.com/whylabs/langkit/blob/main/langkit/docs/modules.md

Each column in the picture represents a whylogs metric. The following example discusses these metrics:
https://github.com/whylabs/whylogs/blob/mainline/python/examples/basic/Inspecting_Profiles.ipynb

Let me know if that answers your question!

**Comment by pradeepdev-1995** [comment]
So how to analyze this report?
![Screenshot from 2024-02-29 10-30-11](https://github.com/whylabs/whylogs/assets/41164884/4b5fd3fe-34e5-460f-8f45-7f9cee5007ec)

consider the second-row 
row : prompt.aggregate_reading_level(aggregate reading level of the input text as calculated by the textstat library)
column : cardinality/est( the estimated unique values for each feature)
the value is 17.00000001
what does this mean?
@FelipeAdachi

**Comment by FelipeAdachi** [comment]
It means that, within the data you profiled (with the size of 50, as shown by `counts/n`), there are approximately 17 different unique values for `prompt.aggragate_reading_level`. This is not the exact value, it's an estimation, denoted by `est` after `cardinality`.

The cardinality value can be more or less useful depending on the feature you're inspecting. In this case, it might not be very interesting. For aggregate_reading_level, the distribution metrics might give more useful information, such as `mean`, `median`, or the quantile values.

**Comment by pradeepdev-1995** [comment]
@FelipeAdachi Okay. So for getting the exact values for aggragate_reading_level,charector_count,automated_readability_index,sentence_count...etc,   how to write the code?
I am looking for the actual values, rather than the distributions like est,mean,median,..etc

**Comment by FelipeAdachi** [comment]
Then you can use langkit directly, like this:

```python
from langkit import llm_metrics, extract
import pandas as pd

df = pd.DataFrame({"prompt":["Hi! how are you?"],"response":["I'm ok, thanks for asking!"]})

enhanced_df = extract(df)

enhanced_df.head()
```

This will calculate metrics in the `llm_metrics` for each row of the dataframe.

I'm closing this issue as it is now langkit-related.

**Comment by pradeepdev-1995** [comment]
@FelipeAdachi 
Thank you so much
