### ISSUE TITLE
Is it possible to host the UI server on localhost?

### ISSUE THREAD

**Issue by snarasimhan1997** [whylabs/whylogs#1482]
## Description

As said in title, I do not see any example where I can start the UI server in my localhost and write data to it (similar to mlflow, evidently.ai etc). Is it assumed that I can only write to the the whylogs UI server? 

- [x] I have reviewed the [Guidelines for Contributing](https://github.com/whylabs/whylogs/blob/mainline/.github/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/whylabs/whylogs/blob/mainline/.github/CODE_OF_CONDUCT.md).

**Comment by jamie256** [comment]
You can view and compare profiles in a notebook environment like in these examples: https://github.com/whylabs/whylogs/blob/mainline/python/examples/basic/Notebook_Profile_Visualizer.ipynb

And you can save those visualizations and reports as html if you wish, but we don't have a local server as part of whylogs. Does that help?
