### ISSUE TITLE
Boolean Python objects treated as unknown type

### ISSUE THREAD

**Issue by bernease** [whylabs/whylogs#149]
If you pass a Python boolean type via a Pandas dataframe, it is treated as **type_unknown** and are not in number or string tracker objects. Perhaps the expected behavior is for us to treat them as boolean type. (We may also want to have a bool tracker or similar object.)

This would match the behavior when we pass in the strings "True" and "False".

**Comment by andyndang** [comment]
So Pandas bool is `numpy.bool_`. It's apaprently a different type from Python's native `bool` 😭

**Comment by jamie256** [comment]
fixed in 1.0.0
