### ISSUE TITLE
Canot cancel out of why.init() interactive modal dialog

### ISSUE THREAD

**Issue by cswarth** [whylabs/whylogs#1510]
## Description

why.init() presents a model dialog in interactive environments like jupyter notebook.  The dialog has "Cancel" and "Ok" buttons.
The Cancel button does not cancel - the only way to make the modal dialog go away is to enter one of the numbers that whylogs considers valid (usually 1 or 2, but sometimes also 3).

- System info
  - Operating system and version: 
  - Browser and version: 
  - Whylogs version 1.3.25
  
- Steps to reproduce:
  - Open jupyter notebook in IntelliJ
  - enter program in cell
    ```
     import whylogs as why
     why.init()
    ```
- evaluate cell, try to cancel model dialog box

![why init cancel](https://github.com/whylabs/whylogs/assets/295428/a974f4d0-df0d-44a8-aff0-1cf0551761f9)

## Suggestions

Cancel should cancel!

## Related

Relates to organization/repo#number 

- [ ] I have reviewed the [Guidelines for Contributing](https://github.com/whylabs/whylogs/blob/mainline/.github/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/whylabs/whylogs/blob/mainline/.github/CODE_OF_CONDUCT.md).

**Comment by jamie256** [comment]
@richard-rogers I think you updated the why.init behavior, can you see if this bug still reproduces on 1.5.0? Is there something we can do to allow the cancel to work?

**Comment by richard-rogers** [comment]
Won't fix -- doesn't reproduce in collab or browser, appears to be an IDE issue rather than whylogs
