### ISSUE TITLE
Retry on 5xx response codes

### ISSUE THREAD

**Issue by richard-rogers** [whylabs/whylogs#1530]
## Description

Currently we do exponential backoff on 429. We should also retry on 5xx. Also specify the set of codes to retry in line 585 of `whylabs_client.py`

- [ ] I have reviewed the [Guidelines for Contributing](https://github.com/whylabs/whylogs/blob/mainline/.github/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/whylabs/whylogs/blob/mainline/.github/CODE_OF_CONDUCT.md).

**Comment by jamie256** [comment]
released in 1.4.2
