### ISSUE TITLE
problems with profiling column names with period in name in pyspark

### ISSUE THREAD

**Issue by jamie256** [whylabs/whylogs#1532]
## Description

Filing on behalf of report.

column names:
"model1.Category", "model1.input_temp"
in a dataframe named df:

collect_column_profile_views(df)

-> No column named "model1.Category" error

- [ ] I have reviewed the [Guidelines for Contributing](https://github.com/whylabs/whylogs/blob/mainline/.github/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/whylabs/whylogs/blob/mainline/.github/CODE_OF_CONDUCT.md).

**Comment by richard-rogers** [comment]
I wasn't able to work around this with backtick escapes in `collect_column_profile_views()`, but renaming the columns works: `input_df.toDF(*(c.replace('.', '_') for c in input_df.columns))`. We might want to maintain a map so we can restore the original column names.
