### ISSUE TITLE
Support passing arbitrary AWS credentials for s3 logging

### ISSUE THREAD

**Issue by Jared-Stufft-Bose** [whylabs/whylogs#192]
`whylogs` currently takes the default AWS profile via `.aws` config or environment variables, but it would be beneficial to be able to directly pass arbitrary AWS credentials to the logger. `whylogs` currently uses `smart-open` to write to S3, which already supports passing a `boto3` session for this purpose with [this PR](https://github.com/RaRe-Technologies/smart_open/pull/201).

Perhaps this can be implemented in the `.whylogs.yaml` or by passing a `boto3` session to the logger and then passing to `smart-open`?

**Comment by lalmei** [comment]
closed in #277
