### ISSUE TITLE
Full Tensor support

### ISSUE THREAD

**Issue by lalmei** [whylabs/whylogs#216]
Current  `log_image` method can take any `np.ndarray` which together with the custom transformation should allow you to log any tensor shape. We would like a smooth experience when a user has a tensor to log. Additionally this use case needs to properly documented

**Comment by schmidt-jake** [comment]
+1. I have a slightly atypical image dataset that has 6 channels, stored in numpy arrays. I'd love to see whylogs support this kind of image format.
