### ISSUE TITLE
[Windows/conda/python3.8] Unable to import whylogs : No matching distribution found for whylabs-datasketches>=2.2.0b1

### ISSUE THREAD

**Issue by dalavayi** [whylabs/whylogs#242]
Hi, 
i was successfully able to install whylogs using : pip install whylogs.
but when i try to import it in my notebooks, i am facing this error
Error: No module named 'google.protobuf.pyext._message'

OS : windows 10, anaconda env
python : 3.8
whylogs version :  0.1.5

i tried uninstalling protobuf and re installing it again. current version of protobuf = 3.17.3

Please help me resolve this error

**Comment by andyndang** [comment]
Hi @dalavayi!

0.1.5 is pretty old - can you use our latest version 0.4.8? The features are pretty similar but we have added tons of work on top:

https://pypi.org/project/whylogs/

**Comment by dalavayi** [comment]
Hi, Thanks for the reply, 
I tried to install whylogs==0.4.8, it is throwing package not found error with `pip install whylogs==0.4.8`
OS: windows 10, anaconda env, python 3.8, pip version 21.1.2.

ERROR: Could not find a version that satisfies the requirement whylabs-datasketches==2.2.0b1 (from versions: 2.0.0b6)
ERROR: No matching distribution found for whylabs-datasketches==2.2.0b1

please help me out here, if i have any version mismatch. 
Thanks

**Comment by patrickphat** [comment]
I can install `pip install whylogs==0.4.8` on python 3.8, pip 21.1.2 but on Linux machine. Can you try to uninstall `pip uninstall whylogs` and try again? @dalavayi

**Comment by dalavayi** [comment]
Getting the same error : 
Please find the output for the command

(mlops_sdk) C:\Users\dalavayi.navya>pip install whylogs==0.4.8
Collecting whylogs==0.4.8
  Using cached whylogs-0.4.8-py3-none-any.whl (1.7 MB)
Collecting pyarrow<4.0.0,>=3.0.0
  Using cached pyarrow-3.0.0-cp38-cp38-win_amd64.whl (12.7 MB)
Collecting smart-open>=4.1.2
  Using cached smart_open-5.1.0-py3-none-any.whl (57 kB)
Requirement already satisfied: tqdm<5.0.0,>=4.60.0 in c:\users\dalavayi.navya\anaconda3\envs\mlops_sdk\lib\site-packages (from whylogs==0.4.8) (4.61.0)
Collecting sklearn<0.1,>=0.0
  Using cached sklearn-0.0.tar.gz (1.1 kB)
Collecting numpy==1.19.3
  Using cached numpy-1.19.3-cp38-cp38-win_amd64.whl (13.3 MB)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\dalavayi.navya\appdata\roaming\python\python38\site-packages (from whylogs==0.4.8) (2.8.1)
Requirement already satisfied: boto3>=1.14.1 in c:\users\dalavayi.navya\appdata\roaming\python\python38\site-packages (from whylogs==0.4.8) (1.16.31)
Requirement already satisfied: pyyaml>=5.3.1 in c:\users\dalavayi.navya\appdata\roaming\python\python38\site-packages (from whylogs==0.4.8) (5.4.1)
Requirement already satisfied: llvmlite<0.37.0,>=0.36.0 in c:\users\dalavayi.navya\anaconda3\envs\mlops_sdk\lib\site-packages (from whylogs==0.4.8) (0.36.0)
Requirement already satisfied: marshmallow>=3.7.1 in c:\users\dalavayi.navya\anaconda3\envs\mlops_sdk\lib\site-packages (from whylogs==0.4.8) (3.12.1)
Requirement already satisfied: protobuf>=3.15.5 in c:\users\dalavayi.navya\anaconda3\envs\mlops_sdk\lib\site-packages (from whylogs==0.4.8) (3.17.3)
ERROR: Could not find a version that satisfies the requirement whylabs-datasketches>=2.2.0b1 (from whylogs) (from versions: 2.0.0b6)
ERROR: No matching distribution found for whylabs-datasketches>=2.2.0b1


> I can install `pip install whylogs==0.4.8` on python 3.8, pip 21.1.2 but on Linux machine. Can you try to uninstall `pip uninstall whylogs` and try again? @dalavayi

**Comment by andyndang** [comment]
Thank you.

This is indeed because we don't have a prebuilt wheel for `whylabs-datasketches` for Windows. It's on our roadmap to address this gap and I'll get back to you soon.

In the meantime, one work around is using [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10) to manage your Python environments. Is it an option for you?

**Comment by dalavayi** [comment]
@andyndang
 hi andy, great to hear that it is on the roadmap in whylogs, will try the alternative suggested. thank you

**Comment by andyndang** [comment]
I'm gonna reopen this until we have windows binaries

**Comment by lalmei** [comment]
windows binary updated  in the latest `whylabs-datasketches==2.2.0b1 ` Thanks @andyndang !
