### ISSUE TITLE
Minimize Core Dependencies

### ISSUE THREAD

**Issue by lalmei** [whylabs/whylogs#246]
There are several required dependencies, and sub dependencies that are not used in whylogs.

The goals is to potentially remove heavy dependencies or seperate them as part of further extensions, so the core features are lightweight. 

Features that require additional dependencies, like data or file specific parsing and logging should be included with an easy extendible framework. e.g. in case of images, Excel Files, segmentation, text etc. 

This is an issue to track this effort.

**Comment by discdiver** [comment]
Trying to install whylogs and it's forcing a downgrade of scikit-learn to sub 1.0. Would be great to support 1.0+.

**Comment by jamie256** [comment]
scikit-learn removed, further modularizing in v1, closing here.
