### ISSUE TITLE
Automatic Constraints Generation from Baseline

### ISSUE THREAD

**Issue by FelipeAdachi** [whylabs/whylogs#254]
It would be nice to have a feature for generating constraints automatically based on a set of profiles that represents a baseline, such as the training data, so that it could be applied during inference time.

For instance, the resulting constraints could be set with thresholds based on statistical properties of the baseline, such as mean or median.

**Comment by datatalking** [comment]
@FelipeAdachi 

Your issue selection is exactly what I've been working on for a data processing tool. I just need some collaboration with you to understand how the data model works.

Can you provide a few pieces of sample data that work with this model?

Can you mock up some pseudo code that roughly outlines your thinking?

**Comment by FelipeAdachi** [comment]
Hi, @datatalking 
That's great!

Sure, let me give some extra thought to this, and I'll get back to you once I have an outline.

**Comment by FelipeAdachi** [comment]
Hi, @datatalking 

In whylogs, constraints are based on Metrics on the DatasetProfile, and not on the raw data itself. Those metrics are aggregates, such as:
- Distribution Metrics
- Frequent Items
- Cardinality
- Types
- Counts

We just merged an initial version of constraints generation with very simple rules under the ` experimental` namespace, to get things started. The best place to see how that works is in the tests:

https://github.com/whylabs/whylogs/blob/7d622c9f6686f7ae43b32be8480345b4e4d08dda/python/tests/experimental/constraints_generation/test_constraints_generation.py#L49

For now, generated constraints will:
- Count Metrics: If the reference contains no null values, create `no_missing_values` constraints for the given column
- Types Metrics: If the type count is non-zero for a list of data types, creates `column_has_non_zero_types` constraints for the types list
- Condition Count Metrics: If a column has a set of conditions attached to it, and the conditions didn't fail once, creates a `condition_meets` constraint

You can also take a look at https://github.com/whylabs/whylogs/pull/1163 for additional context.

My thoughts on the quickest way to expand that would be to leverage the [existing helper functions](https://nbviewer.org/github/whylabs/whylogs/blob/mainline/python/examples/basic/Constraints_Suite.ipynb) to auto-generate constraints per different kinds of Metrics and create new helper constraints as needed.

This would initially scope the constraints generation on single columns. Future directions would be to have multi-column constraints, dataset-level constraints, and conditions between more than one column. But these are all dependent on the progress of other tasks.

Let me know if I can help you with more information!
