### ISSUE TITLE
smart_open is not threadsafe - cannot use with async logging

### ISSUE THREAD

**Issue by andyndang** [whylabs/whylogs#264]
### Summary

in whylogs library you are using async calls for each _do_write:
t = async_wrap(self._do_write, profile, rotation_suffix)
2._do_write , in turn, uses smart_open:
with open(os.path.join(path, self.file_name(profile, ".bin", rotation_suffix)), "wb") as f:
3. smart_open initializes boto3 with default session: https://github.com/RaRe-Technologies/smart_open/blob/f8e60da5a53e1e7ead9d8ca4d3f09cbea04fc337/smart_open/s3.py#L520
4. Session is not thread-safe https://boto3.amazonaws.com/v1/documentation/api/latest/guide/session.html#multithreading-or-multiprocessing-with-sessions

**Comment by lalmei** [comment]
As discussed, this is related to #238 , since the current smart_open api requires a boto3 client as a transport parameter

**Comment by lalmei** [comment]
Fixed in #277
