### ISSUE TITLE
metadata_writer shouldn't be a required parameter

### ISSUE THREAD

**Issue by andyndang** [whylabs/whylogs#268]
### Summary

Users can't create Session without creating a metadata_writer at the moment:
https://github.com/whylabs/whylogs/blob/mainline/src/whylogs/app/session.py#L87

Also SessionConfig requres a `MetadataConfig`:
https://github.com/whylabs/whylogs/blob/mainline/src/whylogs/app/config.py#L214
 but we're passing a Writer:

https://github.com/whylabs/whylogs/blob/mainline/src/whylogs/app/session.py#L105

**Comment by lalmei** [comment]
Closed by #269
