### ISSUE TITLE
Too strict version ranges (and phantom packages) in the `setup.py` on PyPI

### ISSUE THREAD

**Issue by evanfwelch** [whylabs/whylogs#281]
### Summary

When installing whylogs python package into an existing codebase, I encountered some version conflicts. From the perspective of the person downloading the package, here’s what they see as required (pulled this from the .tar.gz on pypi):
install_requires = \
['boto3>=1.14.1',
 'botocore>=1.17.44',
 'click>=7.1.2',
 'llvmlite>=0.36.0,<0.37.0',
 'marshmallow>=3.7.1',
 'matplotlib==3.3.3',
 'mlflow>=1.13.1,<1.14.0',
 'numpy>=1.18.0',
 'openpyxl>=3.0.7,<4.0.0',
 'pandas>=1.0.0',
 'protobuf>=3.15.5',
 'puremagic',
 'pyarrow>=3.0.0,<4.0.0',
 'python-dateutil>=2.8.1',
 'pyyaml>=5.3.1',
 'sklearn>=0.0,<0.1',
 'smart-open>=4.1.2',
 'tqdm>=4.60.0,<5.0.0',
 'whylabs-client',
 'whylabs-datasketches>=2.2.0b1',
 'xlrd>=2.0.1,<3.0.0']
Pandas >=1.0 is not a huge dealbreaker, but things like mlflow==1.13 and matplotlib==3.3.3 or sklearn<0.1… these are probably bloat that don’t need to be in the requirements.
I’d suggest in 0.5.3 or 0.6 you making the transitive dependencies I incur a little slimmer. If MLFlow is just one use case, then make it an extra (e.g. pip install whylogs[mlflow]). Also sklearn is not a real pacakge! It’s just an import shortcut for the package scikit-learn so probably good to remove it from your build!

**Comment by lalmei** [comment]
Removed strict matplolib and phatom dependency in #283 and #282 . I will close it for now since we have an issue open to lighten the dependency management for the core package here #246.
