### ISSUE TITLE
Spark example fails in Databricks with the latest build (0.1.4-b6)

### ISSUE THREAD

**Issue by aptlin** [whylabs/whylogs#364]
### Summary

I am failing to run the [spark demo](https://github.com/whylabs/whylogs-examples/blob/mainline/scala/src/main/scala/WhyLogsDemo.scala) from the examples in Databricks.

### Steps to Reproduce it

1. Set up the cluster with the runtime version `8.1 (includes Apache Spark 3.1.1, Scala 2.12)`
2. Add the whylogs libraries:
  * `ai.whylabs:whylogs-java-spark_3.1.1-scala_2.12:0.1.4-b6`
  * `ai.whylabs:whylogs-java-core:0.1.4-b6`
3. Try running the example in the scala notebook.

### Example

[`export.csv`](https://www.dropbox.com/s/rwfjkh34uauo1rx/export.csv?raw=1) is the file exported from the [example](https://databricks-prod-cloudfront.cloud.databricks.com/public/4027ec902e239c93eaaa8714f173bcfc/4338404698899132/4435723924568266/2419783655524824/latest.html):
```
%scala
import java.time.LocalDateTime

import org.apache.spark.sql.functions._
import org.apache.spark.sql.{SaveMode, SparkSession}
import com.whylogs.spark.WhyLogs._

val path = "/FileStore/sasha/export.csv"
val raw_df = spark.read
    .option("header", "true")
    .csv(path)

val df = raw_df.withColumn("call_date", to_timestamp(col("Call Date"), "MM/dd/YYYY"))

val profiles = df
    .newProfilingSession("FireDepartment") // start a new WhyLogs profiling job
    .withTimeColumn("call_date") // split dataset by call_date
    .groupBy("City", "Priority") // tag and group the data with categorical information
    .aggProfiles() //  runs the aggregation. returns a dataframe of <timestamp, datasetProfile> entries

profiles.write
    .mode(SaveMode.Overwrite)
    .parquet("profiles_parquet")
```

### What is the current *bug* behavior?

Generating a profile fails with
```
Caused by: NoClassDefFoundError: Could not initialize class com.whylogs.core.message.DatasetProperties$TagsDefaultEntryHolder
```

### What is the expected *correct* behavior?

The examples should just work.

### Relevant logs and/or screenshots

See the [full logs](https://www.dropbox.com/s/ttyz92gm7awdhmm/logs.txt?raw=1).

<img width="1346" alt="Screen Shot 2021-11-25 at 5 03 20 PM" src="https://user-images.githubusercontent.com/17913919/143455272-1127b452-a0bd-4589-a41a-83387a86ed31.png">

<img width="1110" alt="Screen Shot 2021-11-25 at 5 11 58 PM" src="https://user-images.githubusercontent.com/17913919/143456554-2174cb3a-0ed5-4e76-8136-cddf460f54fa.png">
<img width="1198" alt="Screen Shot 2021-11-25 at 5 12 18 PM" src="https://user-images.githubusercontent.com/17913919/143456606-f6952841-472a-4863-a771-9e2e8da70ea6.png">
<img width="635" alt="Screen Shot 2021-11-25 at 5 12 40 PM" src="https://user-images.githubusercontent.com/17913919/143456659-d2615082-feaa-439f-a151-d0e4944ebe8e.png">

### Did it work on a previous version ?

Trying whylogs for the first time.

**Comment by andyndang** [comment]
I believe this is because Spark comes with an older version of Protobuf, which is a core dependency for whylogs.

I think we need to build a shadowJar with protobuf shaded rather than pulling it as a runtime dependency. 

Can @aptlin try using the snapshot bundle instead (we haven't published the bundle to the main maven yet):
https://oss.sonatype.org/content/repositories/snapshots/ai/whylabs/whylogs-spark-bundle_3.1.1-scala_2.12/0.1-21aeb7b2-SNAPSHOT/

You can download the jar directly here if you don't want to bother setting up the Snapshot dependency: https://oss.sonatype.org/content/repositories/snapshots/ai/whylabs/whylogs-spark-bundle_3.1.1-scala_2.12/0.1-21aeb7b2-SNAPSHOT/whylogs-spark-bundle_3.1.1-scala_2.12-0.1-21aeb7b2-20210903.224257-1-all.jar

**Comment by jamie256** [comment]
I verified the jar Andy references with a Databricks (version 8.3) cluster, some notes on versions used and an updated example that also uploads the profiles to Whylabs is posted here: https://github.com/whylabs/whylogs-examples/blob/mainline/scala/src/main/scala/WhyLogsScalaLendingClubToWhylabsExample.scala#L2-L4
