### ISSUE TITLE
Update numpy to version 1.21 or later in poetry.lock file

### ISSUE THREAD

**Issue by jamie256** [whylabs/whylogs#414]
### Summary
This is needed so that developer installs with poetry resolve to a version of numpy that has patched known issue:
https://github.com/numpy/numpy/issues/18939

### Steps to Reproduce it
Following whylogs development setup, after running
```
poetry install
```
note the version of numpy is 1.19 which is in the range of vulnerable numpy versions

### What is the expected *correct* behavior?

poetry install should result in numpy install of version 1.21 or later

### Relevant logs and/or screenshots

See https://github.com/advisories/GHSA-6p56-wp2h-9hxr

**Comment by sp6370** [comment]
@jamie256 Hi! Can I take up this issue?

**Comment by jamie256** [comment]
Hi @sp6370 ! Cool to see your interest in helping. This one might be blocked because we don't want to deprecate support for python 3.6 in whylogs yet, and the versions of numpy with the patch (1.21 and higher) are not compatible. I was hoping we might see a backport of the vulnerability to numpy 1.19.x and there is a commit for this: https://github.com/numpy/numpy/pull/20801 but not released yet?

But if you have ideas on how to navigate this we could discuss.

**Comment by jamie256** [comment]
numpy no longer a direct requirement in v1.
