### ISSUE TITLE
Adding support for other languages

### ISSUE THREAD

**Issue by andyndang** [whylabs/whylogs#42]
Track requests for other languages here.

We can create new issues as new language requests come in

**Comment by eliekawerk** [comment]
Scala

**Comment by andyndang** [comment]
@eliekawerk Can you clarify what you need for the Scala support? Scala code can already call into the Java code natively at the moment

**Comment by eliekawerk** [comment]
> @eliekawerk Can you clarify what you need for the Scala support? Scala code can already call into the Java code natively at the moment

True, can use the Java API directly. I missed that!

**Comment by jamie256** [comment]
This is too broad scope, lets track with roadmap items around whylogs v1. We have some scala support not. closing.
