### ISSUE TITLE
Support writing out dataset profiles as json format with mlflow

### ISSUE THREAD

**Issue by jamie256** [whylabs/whylogs#458]
### Summary

you can call mlflow.log_artifact directly and save the profile JSON:
```
summary = profile.to_summary()
open("local_path", "wt", transport_params=transport_params) as f:
    f.write(message_to_json(summary))
mlflow.log_artifact("local_path", your/path")
```

but if you pass a format config to mlflow writer specifying 'json' it isn't supported and instead uses the protobuf bin format.

**Comment by pimonteiro** [comment]
How can i retrieve the profile while inside the start_run()?
