### ISSUE TITLE
Notebook Profile Visualizer doesn't display when set of features not equal

### ISSUE THREAD

**Issue by FelipeAdachi** [whylabs/whylogs#473]
### Summary

When logging two dataframes in different profiles, with one dataframe having one additional feature, `summary_drift_report` displays a blank page. When I remove the additional Feature, the report goes back to normal.

### What is the expected *correct* behavior?

When two profiles have a set of features different from each other, the report should display only the common between both

**Comment by TheMellyBee** [comment]
This looks like a duplicate of  #517 which goes into more description. Going to close this one to prefer the other.
