### ISSUE TITLE
Whylogs in Google Colab

### ISSUE THREAD

**Issue by aswinvk28** [whylabs/whylogs#521]
### Summary

Whylogs was working in Google Colab. Suddenly it stopped generating the output directory. 

### Steps to Reproduce it

Login to google colab and use a sample implementation of whylogs. 

### Example

was trying to use
logger.log({'abc': 'def'})

## What is the current *bug* behavior?

Whylogs is not generating any output directory and its files

### What is the expected *correct* behavior?

Whylogs should generate that output directory fully in google colab. This was supported, but a session reset changed the issue.

### Relevant logs and/or screenshots

![image](https://user-images.githubusercontent.com/1046939/162331070-cb2dc6d6-6119-4220-9480-162c096b4ebd.png)

# Code I used.
pipeline.logger.log({'abc': 'def'})

### Did it work on a previous version ?

The version I worked with is the same version

**Comment by jamie256** [comment]
```logger.log({'abc': 'def'})``` will update a profile in memory. Serialization of profiles occurs with logger.flush() or if the instance of the logger is created in a ```with``` clause this will leverage context manager to implicitly flush() the profiles, like in this notebook:
https://github.com/whylabs/whylogs/blob/mainline/examples/Notebook_Profile_Viewer.ipynb
 or:
 https://github.com/whylabs/whylogs/blob/mainline/examples/log_dataframe.py#L24-L25
 
 ```
with session.logger() as ylog:
    ylog.log({'abc': 'def'})
```

or explicitly flush the profile:

```
pipeline.logger.log({'abc': 'def'})
pipeline.logger.flush()
```
 
 Can you share a little more of the surrounding code if that still isn't working?

**Comment by aswinvk28** [comment]
Thanks, @jamie256 

It worked superbly. Thanks for the notebook as well.
