### ISSUE TITLE
NotebookProfileViewer: Diff from ref. is a confusing name

### ISSUE THREAD

**Issue by FelipeAdachi** [whylabs/whylogs#524]
### Summary

In `NotebookProfileViewer`, for `summary_drift_report`, the column name `Diff from ref.` is a confusing name, as difference gives the idea that the lower the difference, the higher the similarity between profiles, which is not the case.

### What is the expected *correct* behavior?

It should be clear that these values are the same used for the `Drift Detected in X Features` section in the top of the page, and that these are the p-values calculated through KS or Chisquared test.

**Comment by TheMellyBee** [comment]
What about "Difference using p-value"?

**Comment by FelipeAdachi** [comment]
Fixed in https://github.com/whylabs/whylogs/pull/570
