### ISSUE TITLE
NotebookProfileViewer: Error messages in distribution_chart and double_histograms are not helpful

### ISSUE THREAD

**Issue by FelipeAdachi** [whylabs/whylogs#527]
### Summary

When using `distribution_chart` or `double_histogram` with a feature of unsupported type, the error message just shows `Something went wrong.`, instead of actually saying what is wrong about it.

### What is the expected *correct* behavior?

When something goes wrong, the message should be clear on what's wrong. For example, if categorical variables are not supported for `double_histograms`, or similarly for `distribution_chart`

### Relevant logs and/or screenshots

![image](https://user-images.githubusercontent.com/29715545/162487925-5f579ff9-7407-4204-8cde-4020c36e2752.png)

**Comment by jamie256** [comment]
Also remove the prompt to try again, because that incorrectly implies this is an intermittent issue (which in practice it is something with the way we call the method or the data).

**Comment by TheMellyBee** [comment]
This error is html-generated here:

https://github.com/whylabs/whylogs/blob/04f3c31baf0abd727f360805cfc6a2a1e5f53835/src/whylogs/viewer/templates/index-hbs-cdn-all-in-jupyter-distribution-chart.html#L271

The one above has an error handling that we can used to get a more specific error, but other ones don't. They may be able to be redone to have similar error handling.
