### ISSUE TITLE
NotebookProfileViewer-Normalized Frequencies for Distribution Charts

### ISSUE THREAD

**Issue by FelipeAdachi** [whylabs/whylogs#528]
### Summary

Currently, `distribution_chart` shows the absolute count number, and doesn't allow the user to switch to a view where normalized frequencies are displayed.

### What is the expected *correct* behavior?

User should be able to have a parameter in `distribution_chart` to control how the plot is displayed, like:

`visualization.distribution_chart(feature_names="quality",normalized=True)`

**Comment by jamie256** [comment]
+1 on optional parameter for normalizing the distribution chart
