### ISSUE TITLE
NotebookProfileViewer - ability to choose regions in plots in Histograms

### ISSUE THREAD

**Issue by FelipeAdachi** [whylabs/whylogs#530]
### Summary

For numeric features, it is not uncommon to have uncleaned outliers that distort the `double_histogram` plot. If that happens, plot becomes useless, as there is no way to control the region of the plot to be viewed, or to predefined a range to be visualized when calling `double_histogram`

### What is the expected *correct* behavior?

User should either:

- Be able to define a range to view the histograms, like: `visualization.double_histogram(feature_names="total sulfur dioxide", range=[0,100])`
- Interactively select the plot's region to zoom in in the UI

### Relevant logs and/or screenshots

![image](https://user-images.githubusercontent.com/29715545/162491590-f847310e-2a3e-4991-a4af-ea3990ecb6e2.png)

**Comment by TheMellyBee** [comment]
hmm either of options could be done. I'd lean more towards the putting in the range. What do you think, @FelipeAdachi ?

**Comment by FelipeAdachi** [comment]
I think adding a range parameter would mean less effort, so I vote for that. But it doesn't need to be named `range`, maybe there's a better name for it?

**Comment by TheMellyBee** [comment]
This is really a question on do we want to have it keep the same bins but remove the outliers from that range, or recalculate the bins after excluding those outside the range.

To me, I'd prefer that latter as it seems more correct as the outliers would change the shape of the bins. @bernease, @jamie256  and @FelipeAdachi  Thoughts?
