### ISSUE TITLE
NotebookProfileViewer: Wrongly inferred types yields erroneous plots

### ISSUE THREAD

**Issue by FelipeAdachi** [whylabs/whylogs#532]
### Summary

When Categorical Features, such as City Codes, are wrongly inferred as numerical ones, the available chart is `double_histogram` which gives us a plot that is not proper for this type of feature.

**Comment by TheMellyBee** [comment]
Good note. Is there any way for us to have the user tell us if a certain column should inferred like this? Or is it up to the user to make sure that code is set as a str? @jamie256

**Comment by TheMellyBee** [comment]
Right now this is how it was designed, let's make this a feature in the roadmap for the future. @jamie256

**Comment by FelipeAdachi** [comment]
Using ints as categorical encoding vs numerical features is a known issue in data science. Currently (v1), both `double_histogram` and `distribution_chart` are supported for ints. It is up to the user to determine what is the proper plot to use in his/her case.
