### ISSUE TITLE
NotebookProfileViewer: Work with more than two profiles

### ISSUE THREAD

**Issue by FelipeAdachi** [whylabs/whylogs#538]
Currently, the NotebookProfileViewer only accepts two profiles (target and reference). It would be useful to be able to simultaneously compare more than two profiles, with one being the reference profile and the remaining multiple target profiles.

**Comment by TheMellyBee** [comment]
I'm concerned that this would become unreadable if they are all on top of each other. Later on we could introduce a stacked area chart https://observablehq.com/@d3/stacked-area-chart. 

Other idea chatting with @jamie256 what about merging a list of reference profiles together to compare the target with a tail of reference?

**Comment by TheMellyBee** [comment]
I'm going to go ahead and close this, but if we want to reopen it as a design later on we could.
