### ISSUE TITLE
Whylogs is getting blocked in Intel Dev Cloud

### ISSUE THREAD

**Issue by aswinvk28** [whylabs/whylogs#545]
Code

for i in range(1):
      self.logger.log_image(Image.fromarray(np.random.random((10,10))), feature_name="Random Image")
    self.logger.log({'a': 'abcdef'})
    self.logger.flush()
    self.logger.close()

This code does not show any output. But if you comment out the log_image code line, and just log the dictionary, it gives the output. 

Steps to replicate:

Platform:
Intel Dev Cloud

**Comment by aswinvk28** [comment]
Thanks, IDC tested this for me. 
https://community.intel.com/t5/Intel-DevCloud/In-Intel-Dev-Cloud-whylogs-package-is-not-working/m-p/1378455/emcs_t/S2h8ZW1haWx8dG9waWNfc3Vic2NyaXB0aW9ufEwyN0dSSU5PMlJIQVNPfDEzNzg0NTV8U1VCU0NSSVBUSU9OU3xoSw#M4669

There is no bug on this issue, may be its just a platform issue.

**Comment by jamie256** [comment]
How did you create and configure the:
```
self.logger
```

You might want to modify the configuration around where the writers are saving whylogs profiles. The call to logger.flush() will call configured writers to write the output. The default uses a local file writer (like in this example: https://github.com/whylabs/whylogs-examples/blob/mainline/python/GettingStarted.ipynb), but you can pass in a config file to change the behavior: https://github.com/whylabs/whylogs/blob/mainline/examples/.whylogs_local.yaml like in this notebook: https://github.com/whylabs/whylogs-examples/blob/mainline/python/MLFlow%20Integration%20Example.ipynb or you can configure the writers in code like in our Whylabs examples https://github.com/whylabs/whylogs-examples/blob/mainline/python/WhyLabs_Platform.ipynb)

**Comment by aswinvk28** [comment]
I set it same as example provided below:
https://github.com/whylabs/whylogs-examples/blob/mainline/python/MLFlow%20Integration%20Example.ipynb

```python
from whylogs import get_or_create_session
assert whylogs.__version__ >= "0.1.13" # we need 0.1.13 or later for MLflow integration
session = get_or_create_session(".whylogs_mlflow.yaml")
whylogs.enable_mlflow(session)
```

I'm also using MLFlow in my example. But coding it later.

**Comment by TheMellyBee** [comment]
Hi @aswinvk28 I wanted to follow up to see if you're still experiencing problems. We'd love to help get you enjoying whylogs! I'll be watching here, but we also have a wonderful slack community http://join.slack.whylabs.ai/

**Comment by aswinvk28** [comment]
Thanks @TheMellyBee
