### ISSUE TITLE
NotebookProfileVisualizer: Enable existing plots for single profile.

### ISSUE THREAD

**Issue by FelipeAdachi** [whylabs/whylogs#549]
Currently, `summary_drift_report`, `double_histogram`, and essentially every method with exception of `feature_statistics` and `constraints_report` only works when two profiles are passed. It would be helpful to be able to see those plots for only one profile, omitting the information that is relevant only for both profiles, such as Drift calculations. For `double_histograms` and other plots that overlay two distributions, only one distribution can be plotted.

**Comment by TheMellyBee** [comment]
This is true, although I think we should have a separate methods for those to make the API clear.

**Comment by FelipeAdachi** [comment]
This has been fixed  v1.0 onwards.
