### ISSUE TITLE
WhyLogs Community

### ISSUE THREAD

**Issue by techwithshadab** [whylabs/whylogs#60]
Let's have a community on Slack/Discord for discussions, issues, or for getting help from one another.

**Comment by andyndang** [comment]
We have a Slack channel. I'll add it to the README.md! Feel free to join us here: http://join.slack.whylabs.ai/

**Comment by techwithshadab** [comment]
Thanks @andyndang 
That would be really easy for others to join as well if the will be updated to README.md

**Comment by andyndang** [comment]
Definitely! I'm adding it to the README
