### ISSUE TITLE
Broken "Logging" Example Link in the Readme

### ISSUE THREAD

**Issue by cbojer** [whylabs/whylogs#62]
First off, nice work on the library - it looks really exciting!

For your information, I noticed that the link to the "Logging" notebook on the readme is broken.

**Comment by andyndang** [comment]
Thanks for the bug report!
 
I've fixed this in: https://github.com/whylabs/whylogs-python/pull/63

Now you can try out the example with `pip install "whylogs[viz]"` (we don't bundle the viz dependencies in the core module)
