### ISSUE TITLE
pyspark.sql.types.DecimalType recognized as integral by whylogs.api.pyspark.experimental.collect_dataset_profile_view

### ISSUE THREAD

**Issue by ghost** [whylabs/whylogs#620]
## Description

`pyspark.sql.types.DecimalType` columns are recognized as `integral` in profile generated by `whylogs.api.pyspark.experimental.collect_dataset_profile_view`.

- System info
  - Spark Version: 3.0.3
  - PySpark Version: 3.0.3
  - Hadoop Version: 2.7
  - JDK 8
  - Python 3.7.13
  - whylogs 1.0.0

- Steps to reproduce:
  - Colab Notebook to reproduce the observation (end-to-end executable): https://gist.github.com/stiebels/d4941387be46b60d329fb98e3388d7ba

- Plain Code:
```python
from sklearn.datasets import load_wine
from pyspark.sql import SparkSession
spark = SparkSession.builder.master("local[*]").getOrCreate()

df = load_wine(as_frame=True)['data']
df_spark = spark.createDataFrame(df)
df_spark_b = df_spark.withColumn("alcohol",col("alcohol").cast("decimal(10,5)"))
dataset_profile_view = collect_dataset_profile_view(df_spark_b)
dataset_profile_view.to_pandas().transpose()['alcohol']
```

## Suggestions

`pyspark.sql.types.DecimalType` should rather be treated the same as `pyspark.sql.types.DoubleType` and show up as `fractional` in the whylogs profile.

- [x] I have reviewed the [Guidelines for Contributing](CONTRIBUTING.md) and the [Code of Conduct](CODE_OF_CONDUCT.md).

**Comment by jamie256** [comment]
Thanks for the nice example which made it easy to reproduce the issue and fix!

**Comment by jamie256** [comment]
I have this fix along with another pyspark fix here if you want to try it out?
https://pypi.org/project/whylogs/1.0.0.dev0/
```
pip install whylogs==1.0.0.dev0
```

**Comment by ghost** [comment]
Hi @jamie256,

Thanks for picking this up so quickly!

I've ran the notebook above with the version you've cited. Decimals now indeed end up as `fractional`. However, distribution metrics (`distribution/*`) are not calculated (still `NA`). My understanding is that this should be the case though for `fractional` columns?

I've updated the colab notebook, running the version you've cited btw.

**Comment by jamie256** [comment]
Thanks for checking! Reopening this issue to investigate a bit more and add some more tests.

**Comment by jamie256** [comment]
should be fixed in latest release: https://github.com/whylabs/whylogs/releases/tag/v1.0.1
