### ISSUE TITLE
Install with pipenv fails

### ISSUE THREAD

**Issue by sijaira** [whylabs/whylogs#627]
## Description

When trying to install with pipenv whylogs fails with an error in a package "whylogs-sketching"

- System info
  - Operating system and version: Windows 10 Enterprise 19042.1706
  - whylogs v1.0.0- python 3.10.4
  - pipenv 2022.5.2
- Steps to reproduce:
  - Open up a new folder
  - Try to install in a terminal with the line: "pipenv install whylogs"

![whylogs-pipenv-fail](https://user-images.githubusercontent.com/103276110/171697803-3ddff201-d02f-425e-bdfe-fa85d96299cb.png)

## Suggestions

Maybe this is a windows problem. I haven't checked if it can be installed on a linux build. I can install it with just pip so maybe it's just how pipenv install things that is messing it up.

## Related

- [x] I have reviewed the [Guidelines for Contributing](CONTRIBUTING.md) and the [Code of Conduct](CODE_OF_CONDUCT.md).

**Comment by andyndang** [comment]
Looks like you are using Python 3.10. I don't think the binary is available for 3.10 yet (@jamie256 we should limit whylogs to 3.9 for now) so can you  try with 3.9, @sijaira?

**Comment by sijaira** [comment]
Yep using python 3.9 fixed the issue

**Comment by jamie256** [comment]
I also tried with windows 11 + pipenv using python 3.9 which works, but on 3.10 requires building the whylogs-sketching wheel, so we'll restrict the versions to less than 3.10
