### ISSUE TITLE
run tests against example notebooks

### ISSUE THREAD

**Issue by jamie256** [whylabs/whylogs#647]
## Description

The python/examples contains notebooks that we need to cover with tests in our CI so we don't miss them when making changes / fixes.

In v0.7.x we had this workflow: https://github.com/whylabs/whylogs/blob/maintenance/0.7.x/.github/workflows/test-notebook.yml

**Comment by FelipeAdachi** [comment]
Added in https://github.com/whylabs/whylogs/pull/662
