### ISSUE TITLE
Support creating a ColumnProfile from ColumnProfileView

### ISSUE THREAD

**Issue by andyndang** [whylabs/whylogs#665]
## Description

Ramandeep Singh 

Regarding the latest i.e. whylogs v1 API changes.
We moved from just having ColumnProfile
to
ColumnProfile->ColumnProfileView for serializing/deserializing and this is unidirectional.
This leads to the following two issues.
Now you can't update a serialized profile because you'd have to create another ColumnProfile and call merge on its view with the previous view. This is still doable.
You'd lose the type information, since that is stored in Schema for the resolver, present in ColumnProfile, so you can't autogenerate tests on collected profile based on data type, since you don't know the data type.

## Suggestions

If we can somehow access the same Schema object, in theory users can rehydrate the ColumnProfile from a View - this probably a sensible feature request (this assumes that users will pass in the correct config + schema etc…)

Idea: pass in the schema/config to the param. Assuming the configs are the same that should be an equivalent of roundtrip serialization. This way we don't have to deal with storing the config, but still enable roundtrip serder for certain users
```
view = ColumnProfileView.read(...)
column_profile=view.to_profile(schema=schema)
```

## Related

- https://rsqrd-ai.slack.com/archives/C01BMDKKBMZ/p1656528717113839

- [x] I have reviewed the [Guidelines for Contributing](CONTRIBUTING.md) and the [Code of Conduct](CODE_OF_CONDUCT.md).

**Comment by jamie256** [comment]
Still relevant
