### ISSUE TITLE
MLFlow integration: prediction monitoring

### ISSUE THREAD

**Issue by andyndang** [whylabs/whylogs#69]
Breaking up #67.

Support monitoring `python_function` model deployments

https://www.mlflow.org/docs/latest/models.html#deploy-mlflow-models

The implementation takes in a Pandas dataframe - we should be able to ingest them into WhyLogs.

Will require:
* Log rotation
* Storage configuration for Production mode (versus using the model artifact backend in batch mode)

**Comment by vochicong** [comment]
Is there any progression on this? I'd like to see an example of prediction monitoring using whylogs with MLflow.

**Comment by andyndang** [comment]
Update on this:
* We have log rotation
* `whylogs.yml` is not being bundled in the MLflow deployment. This is the blocker at the moment
