### ISSUE TITLE
Track NaN and Infinity separately from `null`

### ISSUE THREAD

**Issue by andyndang** [whylabs/whylogs#700]
## Description

When a system produces NaN or `infinity`, that often indicates bad data or bugs.

## Suggestions

Track these under `n` (count) metric. Maybe under a namespace of counts?

## Related
- Tensorflow tracks the number of `NaN`s: https://github.com/tensorflow/metadata/blob/770c81d26e1bd09faecb2b7940466ad9ddde5483/tensorflow_metadata/proto/v0/statistics.proto#L501

**Comment by jamie256** [comment]
still relevant
