### ISSUE TITLE
Method to revert matplotlib theming

### ISSUE THREAD

**Issue by ibackus** [whylabs/whylogs#73]
The `MatplotlibProfileVisualizer` updates matplotlib rcParams upon initialization.  It should either have

* A method to revert all changes to the previous values
* should use the matplotlib stylesheets context managers: http://matplotlib.org/users/style_sheets.html
* OR should use matplotlib rc context manager: https://matplotlib.org/3.3.2/api/matplotlib_configuration_api.html#matplotlib.rc_context

See also: https://stackoverflow.com/questions/35394564/is-there-a-context-manager-for-temporarily-changing-matplotlib-settings

**Comment by jamie256** [comment]
Deprecated in favor of NotebookProfileVisualizer
