### ISSUE TITLE
Test for broken links in readme and docs

### ISSUE THREAD

**Issue by jamie256** [whylabs/whylogs#740]
## Description

With restructuring of project folders, some links in README.md became broken and we didn't notice. We need a way to automatically test for this.

**Comment by murilommen** [comment]
https://github.com/gaurav-nelson/github-action-markdown-link-check maybe this can help !

**Comment by jamie256** [comment]
> https://github.com/gaurav-nelson/github-action-markdown-link-check maybe this can help !

yep, already started playing with that.
