### ISSUE TITLE
Need a way to check for broken links in notebooks

### ISSUE THREAD

**Issue by jamie256** [whylabs/whylogs#770]
## Description

We have link checking for markdown, but we still missed a broken link in an example notebook. We need a way to check for those in our CI:
e.g. https://github.com/whylabs/whylogs/issues/769
https://whylogs.readthedocs.io/en/stable/examples/integrations/Writing_Profiles.html

**Comment by TheMellyBee** [comment]
Checking to see if we can just hedge the current markdown, else modifying it. But there is this article that is an interesting lead as well https://colab.research.google.com/drive/1zeTZ3S1Z8RvpwRlp4mtJOfNvUwzkSf7W

**Comment by TheMellyBee** [comment]
Sadly there is an external problem with the link checker. It grabs the entire line at times which has " and other characters such as >. 

There is a work around by 1. Ignoring or 2. adding a space between the end of the link and the ending ". Now, this unfortunately is most of the links so 1 would make it not very useful for automation. 2 does work, but is funky. The good news is it still works as a link just fine, and if we ever had to join the string which is rare in .ipynb a strip fixes it. This would take a while to add a space to the end of every string, and it would be difficult for the team to remember. 

For now, we are closing the PR to watch the external bug and revisit.
