### ISSUE TITLE
IPython circular import from running whylogs tests in CI

### ISSUE THREAD

**Issue by FelipeAdachi** [whylabs/whylogs#774]
## Description

![image](https://user-images.githubusercontent.com/29715545/186735205-aa5d6312-3c42-4c4d-a00d-87268056eb80.png)

- System info
  - Operating system and version: 
  - Browser and version: 
- Steps to reproduce:
  - Step
  - Next step

## Related

Relates to organization/repo#number 

- [ ] I have reviewed the [Guidelines for Contributing](https://github.com/whylabs/whylogs/blob/mainline/.github/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/whylabs/whylogs/blob/mainline/.github/CODE_OF_CONDUCT.md).

**Comment by murilommen** [comment]
adding info:

OS: ubuntu-latest 
python 3.8

steps to repro:
```python
from whylogs.viz import SummaryDriftReport
```
