### ISSUE TITLE
whylogs comet-ml writer

### ISSUE THREAD

**Issue by jamie256** [whylabs/whylogs#799]
## Description
It would be useful to have a writer integration with comet-ml for whylogs and example notebook.

**Comment by andyndang** [comment]
Looks like it's pretty straight forward to write
https://www.comet.com/docs/v2/guides/data-management/using-artifacts/#create-an-artifact

```
from comet_ml import Experiment, Artifact

experiment = Experiment(
    api_key="<Your API Key>",
    project_name="<Your Project Name>"
)

artifact = Artifact(artifact_name="artifact-name", artifact_type="dataset")
artifact.add("path/to/my/file.csv")
experiment.log_artifact(artifact)
experiment.end()
```
