### ISSUE TITLE
requests package not described as dependency for whylogs[whylabs]

### ISSUE THREAD

**Issue by jamie256** [whylabs/whylogs#804]
## Description

if you don't have the requests package and are using the whylabs package you will hit errors when making calls to whylabs using the client. The bug is missing dependency in whylabs-client package, but we should mitigate this in whylogs.

**Comment by TheMellyBee** [comment]
That makes sense. Is this something we should add as a dependency in the make file for whylogs[whylabs]?

**Comment by TheMellyBee** [comment]
@jamie256 poetry is still running for this. Could you run it on yours as well overnight? dev/melly/bug/add-requests-package, but I don't think I pushed sadly before running poetry update. 

Added requests to whylabs packages, ran poetry add requests, and then running poetry update
