### ISSUE TITLE
filtered segmentation should not require columnar segmentation

### ISSUE THREAD

**Issue by jamie256** [whylabs/whylogs#808]
## Description

Usability issue with helper functions that create segments for schema override: segmentation on column is simple, but using filters without column segments is error prone. Need to create helper function to simplify.

**Comment by TheMellyBee** [comment]
Are you thinking this would be like a helper function that runs a column segmentation before filtering? 

Would like more clarity on that first bit.

**Comment by jamie256** [comment]
No, we have columnar segmentation and utilities for that.

We also have filters which run before column segmentation.

What is awkward here is that you might want to filter based on column values, e.g. subset of the data where "col1=x1", now that might be the full extent to your intended segmentation but whylogs segmentation require you also specify a column for segmentation (which you might not need, so if you segment on col1 things work but its an extraneous requirement to specify that column in this scenario since you already limited the data to only have the single value for that column).
