### ISSUE TITLE
Support serializing dataset profile view to bytes

### ISSUE THREAD

**Issue by andyndang** [whylabs/whylogs#821]
## Description

User would like to serialize a DatasetProfileView to a byte string rather than writing to file directly. They can have million of profiles so writing to file always isn't a good strategy
## Related

- [x] I have reviewed the [Guidelines for Contributing](https://github.com/whylabs/whylogs/blob/mainline/.github/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/whylabs/whylogs/blob/mainline/.github/CODE_OF_CONDUCT.md).

**Comment by goodwanghan** [comment]
Thanks, can you make it pickle compatible? Implementing `__getstate__` and `__setstate__`
