### ISSUE TITLE
Support round trip pickling with DatasetProfileView

### ISSUE THREAD

**Issue by andyndang** [whylabs/whylogs#822]
## Description

Related to https://github.com/whylabs/whylogs/issues/821

Support pickling

**Comment by jamie256** [comment]
See https://github.com/whylabs/whylogs/blob/maintenance/0.7.x/src/whylogs/core/datasetprofile.py#L125-L130

**Comment by jamie256** [comment]
https://github.com/whylabs/whylogs/pull/827
