### ISSUE TITLE
Link to our doc/nbviewer for example notebooks 

### ISSUE THREAD

**Issue by jghoman** [whylabs/whylogs#831]
## Description

The constraint violation report is [not being rendered](https://github.com/whylabs/whylogs/blob/mainline/python/examples/basic/Metric_Constraints.ipynb) (end of notebook, cells 35+) when viewing the example notebook in Github:
<img width="1341" alt="Screen Shot 2022-09-16 at 1 11 51 AM" src="https://user-images.githubusercontent.com/95350/190689059-3fa8b6cd-8f5f-4ed0-a367-ad38188c5954.png">

Compare this with the collab (or local) render:
<img width="1109" alt="Screen Shot 2022-09-16 at 1 16 10 AM" src="https://user-images.githubusercontent.com/95350/190689096-314a4d8e-39ad-4f30-8700-ef5e6ffdbb83.png">

I Googled around but the causes of render issues are so legion it's hard to know what might be causing this.  The underling cell has quite a bit of javascript - maybe there's some cross site library issue (totally out of my subject area here)?

This is suboptimal because folks won't be able to see what the constraint report looks like, without going to the collab site or running the notebook themselves.

If we can't find a fix, maybe at least a note pointing readers to the collab site?

- [x] I have reviewed the [Guidelines for Contributing](https://github.com/whylabs/whylogs/blob/mainline/.github/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/whylabs/whylogs/blob/mainline/.github/CODE_OF_CONDUCT.md).

**Comment by andyndang** [comment]
I don't think this is an issue. GitHub just doesn't support rendering HTML elements in a notebook and this is a github limitation. The example renders fine in our doc site: https://whylogs.readthedocs.io/en/latest/examples/advanced/Constraints_Suite.html

**Comment by andyndang** [comment]
https://docs.github.com/en/repositories/working-with-files/using-files/working-with-non-code-files#working-with-jupyter-notebook-files-on-github

> The interactive features of the notebook, such as custom JavaScript plots, will not work in your repository on GitHub.com. For an example, see [Linking and Interactions.ipynb](https://github.com/bokeh/bokeh-notebooks/blob/main/tutorial/06%20-%20Linking%20and%20Interactions.ipynb).

**Comment by andyndang** [comment]
Don't think it's something we can fix so I'm gonna close the the issue.

Same notebook renders fine based on the official recommendation of using nbviewer: https://nbviewer.org/github/whylabs/whylogs/blob/mainline/python/examples/basic/Metric_Constraints.ipynb

**Comment by jghoman** [comment]
If I'm evaluating WhyLogs and trying to learn more about it, I would read this notebook and and be confused.  We directly [link](https://github.com/whylabs/whylogs#examples) to this (and in the other [examples](https://github.com/whylabs/whylogs/tree/mainline/python/examples)).  If we don't want people consuming these notebooks in Github, we should probably link to somewhere else.

**Comment by FelipeAdachi** [comment]
An alternative is to point to the examples in readthedocs, like https://whylogs.readthedocs.io/en/latest/examples/advanced/Constraints_Suite.html

We already do that from inside the examples, but the links in the README point to those in Github. The thought was prevent moving the user between places back and forth, but I agree that Github not rendering HTML well is an issue.

**Comment by andyndang** [comment]
@jghoman good call! We should link to nbviewer/doc site instead rather than the GitHub link!

**Comment by andyndang** [comment]
Updated the title and re-opened the issue

**Comment by jghoman** [comment]
Cool.  Will spin up a patch.

**Comment by jamie256** [comment]
I'm fine with nbviewer/docs links, colab also works. We might want to consistently add the "open in colab" button to our examples so users have an easier time switching from reading to trying it out as an escape hatch from nbviewer (doesn't need to be done at the same time, more of a follow up note).
