### ISSUE TITLE
uploading several profiles sequentially to WhyLabs is slower than it should be

### ISSUE THREAD

**Issue by jamie256** [whylabs/whylogs#865]
## Description

The WhyLabs writer creates a new client on each upload if you follow our examples and SSL handshake can take a while. Suggest we look into caching the api client in the result set's writers getters.

- [ ] I have reviewed the [Guidelines for Contributing](https://github.com/whylabs/whylogs/blob/mainline/.github/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/whylabs/whylogs/blob/mainline/.github/CODE_OF_CONDUCT.md).

**Comment by christinedraper** [comment]
Some timings from today for logging and loading 62 batches of performance metrics + 62 batches of profiles (2 features, 1000 rows):
* 15 seconds - v0.7.5 + whylabs-client 0.3.0, instantiating a single WhyLabs writer and calling writer.write
* 2 min 07 seconds - v1.1.12 + whylabs-client 0.4.0, calling profile.write
* 1 min 28 seconds - v1.1.12 + v0.4.0, instantiating a single WhyLabs writer and calling writer.write
* 1 min 28 seconds - v1.1.12 + v0.4.0, single writer with rolling logger
* 2 min 22 seconds - v1.1.0 + v0.3.0, single writer with rolling logger
* 2 min 59 seconds - v1.1.0 + v0.3.0, calling profile.write
* 2 min 26 seconds - v1.1.0 + v0.4.0, single writer with rolling logger
* 1 second - v1.12 logging without loading
* 13 seconds - v0.7.5 logging without loading

So v1.1.12 is faster than v1.1.0 by about 0.5 seconds per upload; overhead from initializing logger on each upload is c. 0.3 seconds. But most importantly, the difference between running async in v0 and sync in v1 is increasing loading time by a factor of at least 6.
