### ISSUE TITLE
When uploading segmented profiles the api key parameter doesn't override env api key value

### ISSUE THREAD

**Issue by jamie256** [whylabs/whylogs#866]
## Description

If you specify an api key in the whylab's writer as an override for an env variable set api key, the parameter should take precedence but it doesn't. This is specific to uploading segmented profiles.

`results.writer('whylabs').option(api_key=self.api_key).option(org_id=self.org_id).write(dataset_id=self.dataset_id)`

**Comment by christinedraper** [comment]
This is still a problem in whylogs 1.1.14. Weirdly, it appears to write one segment and then fail.
