### ISSUE TITLE
Making DatasetProfileViews is ambiguous/confusing

### ISSUE THREAD

**Issue by naddeoa** [whylabs/whylogs#869]
## Description

I'm creating empty `DatasetProfileView`s right as part of our Ray examples. I'm using the empty view as the seed in a reduce while merging many views together. Its unclear what the "right" way of making a view is supposed to be. There are two options that I know of.

```python
# ex1
view = DatasetProfile().view()

# ex2
view = DatasetProfileView(columns={}, dataset_timestamp=0, creation_timestamp=0)
```

This raises a lot of questions from the user's point of view.
- The constructor args of `DatasetProfileView` are apparently optional because I don't supply them in ex1, so why are they required if you try to make a view directly?
- What function does the `dataset_timestamp` and `creation_timestamp` serve and how was it implicitly set in ex1?
- What happens if I set the timestamps to 0 and just use the view I make in ex2 as a reduce seed with other profiles that are actually tracking data?
- Am I even supposed to be making views myself?

## Suggestions

At the very least, `DatasetProfileView()` should be updated to make `columns`, `dataset_timestamp`, and `creation_timestamp` optional. That would at least hide some details and avoid prompting further questions on the topic. Some docs on the `DatasetProfileView` would go a long way as well though.

## Related

Relates to organization/repo#number 

- [x] I have reviewed the [Guidelines for Contributing](https://github.com/whylabs/whylogs/blob/mainline/.github/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/whylabs/whylogs/blob/mainline/.github/CODE_OF_CONDUCT.md).

**Comment by jamie256** [comment]
I agree with making the parameters to DatasetProfileView optional, but the class was not designed with user instantiation in mind as we expected users to also start with a DatasetProfile and then convert for serialization or analysis. The map reduce scenario is a compelling case to allow for an empty DatasetProfileView. How about we provide a DatasetProfileView.zero() method for this in line with the reduce seed?

**Comment by naddeoa** [comment]
I'm actually running into this again trying to get whylogs working nicely with BigQuery, which is also doing a distributed reduce. It's worth mentioning that I think the real issue here is that we can't serialize `DatasetProfile`, which is forcing me to try to get everything working with `DatasetProfileView`, but I'm sacrificing a lot of performance (and maybe making some of our estimated values in our profiles worse) by converting to and merging into views way more than I would have to if I was running this on a single host.

That might be a larger conversation, but as long as we're forced to use `DatasetProfileView` because of serialization issues, then having something like `.zero()` would work. 

Also, why is it called `zero`? I've seen that  pattern among the metric components.
