### ISSUE TITLE
Documentation for whylogs architecture

### ISSUE THREAD

**Issue by andyndang** [whylabs/whylogs#875]
## Description

We should add some documentation around the underlying sketching technique of whylogs, discusses relative errors etc....

**Comment by naddeoa** [comment]
I've got a few diagrams that I made as part of ramping up on the whylogs design. I'll leave them here for a second look to make sure they pass a sniff test, then we can incorporate them into the wiki or something.

The first one is a sequence diagram of the important parts of logging data.

![image](https://user-images.githubusercontent.com/1233709/192620269-418dcdd5-6792-4dc0-8e33-bd2da8e04103.png)

The second one is a high level overview of the types of entities that exist in whylogs and how they relate to each other.

![image](https://user-images.githubusercontent.com/1233709/192619964-e6b81595-2b66-4128-ade4-69f7ca30d9d2.png)

@jamie256
