### ISSUE TITLE
mypy is not catching signature issues in core classes in our CI

### ISSUE THREAD

**Issue by jamie256** [whylabs/whylogs#888]
## Description

mypy is enabled in our pre-commit hooks but seems to be missing issues in the signatures of classes such as:
DatasetProfile's get_default_path method has no type annotation for the input parameter. Why is this not showing up in pre-commit checks?

**Comment by andyndang** [comment]
So the reason is that pre-commit config doesn't use pyproject.toml config. We'll need these at least:

```
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
      - id: mypy
        language: system
        args:
          [
            --disallow-incomplete-defs,
            --disallow-untyped-defs,
            --explicit-package-bases,
            --namespace-packages,
            --show-error-codes,
          ]
        exclude: ^(python/tests/|python/examples/|python/examples/integration/|python/whylogs/core/proto/|python/docs/|python/whylogs/viz/html/|java)
```

**Comment by jamie256** [comment]
Not sure I follow the conclusion there @andyndang, but willing to try out adding the hook somewhere else if that's what you think is going on. We are catching things in the existing mypy pre-commit hook. mypy is not categorically missing everything in whylogs CI. Running locally `make pre-commit` shows same failures and passing state as what we get in the CI.

See example here where I intentially changed the return type from Preprocessing method from None to bool:
https://github.com/whylabs/whylogs/actions/runs/3152481944/jobs/5127755443#step:11:97

**Comment by andyndang** [comment]
@jamie256 Here's theh config in [pyproject.toml](https://github.com/whylabs/whylogs/blob/mainline/python/pyproject.toml) - those args are enabled based on this

```
[tool.mypy]
disallow_incomplete_defs = true
disallow_untyped_defs = true
explicit_package_bases = true
files = ["whylogs/**/*.py"]
namespace_packages = true
show_error_codes = true
plugins = [
    "numpy.typing.mypy_plugin"
]
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | examples
    | examples/integration
    | tests
    | whylogs/core/proto
    | whylogs/viz/html
    | docs
    | *.pyi
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''
```

**Comment by andyndang** [comment]
So `make pre-commit` is not using this config - the pyproject.toml is being picked up by pyCharm and I'm seeing different things. We should align both of them
