### ISSUE TITLE
adding nlp and cv semantic drift samples

### ISSUE THREAD

**Issue by LangDaoAI** [whylabs/whylogs#918]
Hi,

Great features and post about https://whylabs.ai/blog/posts/detecting-semantic-drift-within-image-data,  However, I have not found any samples from the repository about nlp and cv semantic drift samples. So, I request adding such samples into the repository.

thanks!

**Comment by TheMellyBee** [comment]
Hello! 

Thanks for logging an issue! That article was written with [v0](https://pypi.org/project/whylogs/0.7.10/) which you can still work with. We released [v1](https://pypi.org/project/whylogs/1.1.9/) which does have image logging capabilities which you can check out in this [notebook](https://github.com/whylabs/whylogs/blob/bda39292c2fad72424e7ab6a7f5cc74328a8f7b2/python/examples/advanced/Image_Logging.ipynb). The rest is on the roadmap, and we will announce the release, which would include examples, both here and in our slack community: Robust & Responsible AI which you can join [here](https://join.slack.com/t/rsqrd-ai/shared_invite/zt-187pjz5xv-dyDgSzFw6HBNy6S4h6Ot9Q). 

Thanks! 
Melly

**Comment by TheMellyBee** [comment]
Closing due to it being on our roadmap and answered.
