### ISSUE TITLE
Update docs on whylogs release 

### ISSUE THREAD

**Issue by TheMellyBee** [whylabs/whylogs#923]
## Description
Docs have release walk through for fully manual, needs updated now that the automation is complete.

- [X ] I have reviewed the [Guidelines for Contributing](https://github.com/whylabs/whylogs/blob/mainline/.github/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/whylabs/whylogs/blob/mainline/.github/CODE_OF_CONDUCT.md).

**Comment by jamie256** [comment]
> Docs have release walk through for fully manual, needs updated now that the automation is complete.

Can you clarify this issue? I am not parsing that description: where is there a manual process that needs automation? Which docs are you referring to?

We build docs in our automation and update these in the release:
https://whylogs.readthedocs.io/en/latest/
