### ISSUE TITLE
More information in Constraints report would be useful

### ISSUE THREAD

**Issue by jamie256** [whylabs/whylogs#948]
## Description

Constraints would be more useful if they contained more information in the report - in particular,  counts for how many records passed/failed.

- [x] I have reviewed the [Guidelines for Contributing](https://github.com/whylabs/whylogs/blob/mainline/.github/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/whylabs/whylogs/blob/mainline/.github/CODE_OF_CONDUCT.md).

**Comment by FelipeAdachi** [comment]
this was fixed on https://github.com/whylabs/whylogs/pull/976
