### ISSUE TITLE
[viz] Categorical features have mean displayed on report as "0"

### ISSUE THREAD

**Issue by FelipeAdachi** [whylabs/whylogs#953]
## Description

Features that don't have a distribution metric have a displayed mean of 0:

![image](https://user-images.githubusercontent.com/29715545/200327835-159756b1-3a4b-4933-b021-bc578c4e57ce.png)

This is misleading, as the mean is non-existent, and not 0. A numerical feature could have a legitimate mean of 0, and we would not have a way of discerning between the two "0"s

In these cases, showing "na", "-", "null" or something similar would be more appropriate

- System info
  - Operating system and version: 
  - Browser and version: 
- Steps to reproduce:
  - Step
  - Next step

## Related

Relates to organization/repo#number 

- [ ] I have reviewed the [Guidelines for Contributing](https://github.com/whylabs/whylogs/blob/mainline/.github/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/whylabs/whylogs/blob/mainline/.github/CODE_OF_CONDUCT.md).

**Comment by ddxgz** [comment]
Hi, this seems happening again. In the Pandas DataFrame generated from profile view, the value of `distribution/mean` is `0.0` for string columns, while:
- `distribution/max` and `min` are `NaN`
- `distribution/median` and quantiles are `None`

System info
Version: 1.3.24

**Comment by FelipeAdachi** [comment]
Hi @ddxgz ,

Thanks for reporting this.
I'll inspect this and reopen the issue if needed.
