### ISSUE TITLE
Can't pass a schema to logger v1.1.10

### ISSUE THREAD

**Issue by msharp-shop** [whylabs/whylogs#956]
## Description

I was trying to set up a segmentation in a streaming case, but found that I couldn't even pass a schema.

- System info
  - Operating system and version: macOS 12
  - Browser and version: n/a
- Steps to reproduce:
  - logger = why.logger()
  - logger.log(df, schema=DatasetSchema())

<img width="477" alt="image" src="https://user-images.githubusercontent.com/110247659/200431931-8a757a5c-4a91-45c7-afdd-86ea5bc5f3d6.png">

## Suggestions

Expected to be able to pass a DatasetSchema.  See docs here:
https://whylogs.readthedocs.io/en/latest/api/whylogs/api/logger/index.html#whylogs.api.logger.log

## Related

Relates to organization/repo#number 

- [ ] I have reviewed the [Guidelines for Contributing](https://github.com/whylabs/whylogs/blob/mainline/.github/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/whylabs/whylogs/blob/mainline/.github/CODE_OF_CONDUCT.md).

**Comment by jamie256** [comment]
Thanks for filing this issue, will fix the interface for tomorrow's release! Note to avoid this issue in the meantime, you can pass the schema in where you instantiate a logger:
```
logger = why.logger(schema=DatasetSchema())
logger.log(df)
```
