### ISSUE TITLE
Use DatasetSchema with Spark collect_dataset_profile_view() 

### ISSUE THREAD

**Issue by gramhagen** [whylabs/whylogs#961]
## Description

I'd like to customize the metrics being tracked when I generate a profile view using the experimental Spark API, similar to the signature of why.log()

```python
profile_view = collect_dataset_profile_view(df, schema=DatasetSchema(resolvers=MyCustomResolver()))
```

## Suggestions

it's pretty straightforward to pass that through collect_column_profile_views() to whylogs_pandas_map_profiler(), and ultimately into why.log(). I've tested that change locally and it works fine. Before I submitted a PR, I wanted to check if there are any concerns with adding that optional field?

- [X ] I have reviewed the [Guidelines for Contributing](https://github.com/whylabs/whylogs/blob/mainline/.github/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/whylabs/whylogs/blob/mainline/.github/CODE_OF_CONDUCT.md).

**Comment by jamie256** [comment]
Hi @gramhagen,

Sure, we would welcome a contribution in this area!

Note: there are some complexities in serializing what might be in the DatasetSchema and also handling segmentated profiles, I know some cases won't work without some significant changes. But if you have some limited scope changes that unblock your scenario then that sounds great to me! Its still experimental so its a good place to have input and help!

If you want to proceed with a change, I would suggest we try to keep the scope focused on your scenario to support customizing the set of metrics tracked. I can follow up with some edge case handling and then later add segmentation support.

**Comment by gramhagen** [comment]
Sounds good, let me know what your thoughts are on the PR @jamie256
