### ISSUE TITLE
Deserialization error with logger with DatasetSchema

### ISSUE THREAD

**Issue by msharp-shop** [whylabs/whylogs#966]
## Description

Recieving a `whylogs.core.errors.DeserializationError` when trying to read the results of a logger with segmentation.  This is using the latest version of whylogs 1.1.11

- System info
  - Operating system and version: macOS 13.0
  - Browser and version: n/a
- Steps to reproduce:
  - You can run the following script
```
import os
import time
import pandas as pd
import whylogs as why
from sklearn.datasets import load_iris

from whylogs.core.schema import DatasetSchema
from whylogs.core.segmentation_partition import segment_on_column

print("Setting up")
tmp_path = "logs"
if not os.path.isdir(tmp_path):
    os.makedirs(tmp_path)

why_logger = why.logger(
    mode="rolling", interval=5, when="S", base_name="segmentation_fault",
    schema=DatasetSchema(segments=segment_on_column("target"))
)
why_logger.append_writer("local", base_dir=tmp_path)

iris = load_iris(as_frame=True).frame

print("Running logger")
for i in range(30):
    why_logger.log(iris.sample())
    time.sleep(1)

why_logger.close()

print("Print results")
all_files = [f for f in os.listdir(tmp_path) if not f.startswith('.')]
for file in all_files:
    path = os.path.join(tmp_path, file)
    result = why.read(path)
    print(result)
```

<img width="565" alt="image" src="https://user-images.githubusercontent.com/110247659/200955466-f84b6181-ec3f-4037-8790-490949e267f3.png">

## Suggestions

Expect to be able to read the `.bin` files.  The naming convention is different from regular profiles so I'm guessing these are segmentation files?  I saw [this tutorial](https://nbviewer.org/github/whylabs/whylogs/blob/mainline/python/examples/advanced/Segments.ipynb#Writing-the-Segments-to-Disk) which talks about writing segmentation files to disk, but I couldn't find docs anywhere about reading them.

## Related

Relates to organization/repo#number 

- [ ] I have reviewed the [Guidelines for Contributing](https://github.com/whylabs/whylogs/blob/mainline/.github/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/whylabs/whylogs/blob/mainline/.github/CODE_OF_CONDUCT.md).

**Comment by jamie256** [comment]
Thanks for the detailed repro steps! This is very nicely filed issue.

I think this is because the segmented profiles are written using a whylogs serialization v0 format in the 'local' and 'whylabs' writers, which then fails the why.read.

Maybe trying to fallback to the v0 format reader would make this less confusing if users do have v0 files around: https://github.com/whylabs/whylogs/blob/mainline/python/whylogs/migration/converters.py#L108

Also, there isn't a good reason to have the local writer using the v0 format for segments, that was a mistake.

**Comment by jamie256** [comment]
Candidate fix in dev release: https://pypi.org/project/whylogs/1.1.12.dev0
