### ISSUE TITLE
creation_timestamp on merged profiles change with merge order

### ISSUE THREAD

**Issue by murilommen** [whylabs/whylogs#973]
## Description

```python
import whylogs as why

view1 = why.log({"a":1}).view()
view2 = why.log({"a":1}).view()

view1.merge(view2).creation_timestamp == view2.merge(view1).creation_timestamp
Out[23]: False
```

IMO they should always take into account the lowest creation_timestamp for a merged profile, right? 
What happens is that we always stick with the first one.
Same thing happens for `DatasetProfile().view().merge(view1)`, as it gets the empty profile's timestamp instead.

- [x] I have reviewed the [Guidelines for Contributing](https://github.com/whylabs/whylogs/blob/mainline/.github/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/whylabs/whylogs/blob/mainline/.github/CODE_OF_CONDUCT.md).

**Comment by jamie256** [comment]
fixed by https://github.com/whylabs/whylogs/pull/978
