### ISSUE TITLE
Stop using s3fs 

### ISSUE THREAD

**Issue by andyndang** [whylabs/whylogs#99]
S3fs consumes aiobotocore, which pins botocore version: https://github.com/aio-libs/aiobotocore/issues/840

With new Pip resolution logic, we are seeing failures when consuming whylogs in an environment that depends on a different version of boto3.

This means that users cannot install whylogs AND use different version of boto3. This is a major blocker for using the package for most people. 

Solution: need to stop using s3fs

**Comment by lalmei** [comment]
Closed in #140
